sudo: false
dist: trusty
language: node_js

node_js:
  - stable
  - 6
  - 4

after_success:
  - npm install codecov
  - npm run codecov

notifications:
  email:
    on_success: change
    on_failure: always
